a= "it's not over Until its over\n"
print(a)
print(len(a))
print(a.lower())
print(a.upper())
print(a.capitalize())
print(a.replace("Until","til"))
print(a[1])
print(a.find("over"))
print(a[0:26])
print(a[:])
print(a[::-1])
print(a.find("over"))
print(a[1:5:2])
print(10*a)
print("enter the string: ")
b= input()
c=int(b)
print(type(c))